### ISSUE TITLE
Fatal Error 1.1.0

### ISSUE THREAD

**Issue by miklb** [mAAdhaTTah/WP-Gistpen#250]
```
Fatal error: Uncaught Error: Class 'WPUpdatePhp' not found in /wp-gistpen/wp-gistpen.php:40 Stack trace: #0 /wp-admin/includes/plugin.php(1897): include() #1 /wp-admin/plugins.php(172): plugin_sandbox_scrape('wp-gistpen/wp-g...') #2 {main} thrown in /plugins/wp-gistpen/wp-gistpen.php on line 40
```

to be clear I used `wget` to download 1.1.0 release from GitHub

**Comment by mAAdhaTTah** [comment]
I think this may be a buggy deploy. Looks like I never deployed it to my personal site to verify. Will fix asap.

**Comment by mAAdhaTTah** [comment]
Try `1.1.1`

**Comment by mAAdhaTTah** [comment]
Edit: 1.1.1

**Comment by miklb** [comment]
Seeing the same error

**Comment by mAAdhaTTah** [comment]
@miklb Did you see the edit and used `1.1.1`? I accidently posted 1.1.0, which I didn't reupload (cuz I feared there may be SVN issues, so I deployed a new version to GH & WP.org).

**Comment by miklb** [comment]
I'll try the wp.org link, but I did use `1.1.1` and that's what shows on the plugin page.

**Comment by mAAdhaTTah** [comment]
What's on .org & GH _should_ be the same. Looking at the code in the zip, it looks fine, so I'm not sure what's going on here :/

**Comment by miklb** [comment]
¯\_(ツ)_/¯ 

wp.org link works, but for what ever reason on my site, I'm still not able to create a gist. There's no editor, just the top meta box . I'll try it out on a local vanilla install when I get a chance.

**Comment by mAAdhaTTah** [comment]
lol how do you always end up with all the weird issues?

**Comment by mAAdhaTTah** [comment]
On the editor screen, can you provide any error messages from the console? it's a React app now, so this should (hopefully) be a bit easier to debug.

**Comment by mAAdhaTTah** [comment]
I'm going to close this, as I'd need more information to investigate. If the issue reappears, feel free to reopen.
